name: "Build customized NixOS LiveCD ISO"
on:
  push:
  schedule:
    - cron: '0 12 * * *'
jobs:
  buildiso:
    if: startsWith(github.event.head_commit.message, 'buildiso:')
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H')"
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0
    - name: Install nixFlake
      uses: cachix/install-nix-action@v10
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20200618_377345e/install
    - name: Configure Nix to enable flake
      run: echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
    - name: Build LiveCD ISO image
      run: |
        nix flake update --recreate-lock-file
        nix build ".#niximg"
        cp "result/iso/$(ls "$(readlink result)/iso/")" ./niximg.iso
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{steps.date.outputs.date}}
        release_name: ${{ steps.date.outputs.date }}
        body: This is a nightly NixOS LiveCD build built on ${{ steps.date.outputs.date }}. See [homepage](https://github.com/LEXUGE/nixos) for more information.
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./niximg.iso
        asset_name: niximg-${{ steps.date.outputs.date }}.iso
        asset_content_type: application/x-iso9660-image
    - name: Push release to the Telegram channel
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          The `${{ github.workflow }}` workflow triggered at `${{ steps.date.outputs.date }}` have created a new [release](${{ steps.create_release.outputs.html_url }}).
          See [homepage](https://github.com/LEXUGE/nixos) for more information.
	  #niximg #nightly
