name: "Release clean-up"
on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
    - uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 10
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
